#pragma once

const char MJOLNIR_WEB_PAGE[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MJÖLNIR // WORTHINESS</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#050608;color:#f2f2f2;font-family:Arial,Helvetica,sans-serif;display:grid;place-items:center}.shell{width:min(920px,94vw);padding:42px 28px;border:1px solid #30343a;background:linear-gradient(145deg,#0b0d10,#050608);box-shadow:0 0 70px #000;position:relative}.top{display:flex;justify-content:space-between;color:#777d85;font-size:11px;letter-spacing:2px}h1{margin:26px 0 4px;font-size:clamp(28px,6vw,62px);letter-spacing:7px;line-height:1;font-weight:800}.sub{color:#858a91;letter-spacing:4px;font-size:12px}.score{text-align:center;margin:58px 0 24px}.num{font-size:clamp(76px,17vw,150px);line-height:.85;font-weight:900;letter-spacing:-7px}.label{margin-top:18px;font-size:clamp(26px,5vw,48px);font-weight:900;letter-spacing:8px}.status{margin:8px auto 0;color:#777d85;font-size:12px;letter-spacing:2px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin-top:50px;background:#30343a}.cell{background:#0b0d10;padding:20px}.key{color:#686e76;font-size:10px;letter-spacing:2px;margin-bottom:9px}.value{font-size:20px;font-weight:700}.quote{margin-top:30px;padding:20px;border-left:2px solid #777;color:#b8bdc4;font-size:14px;letter-spacing:1px}.foot{margin-top:34px;color:#454a50;font-size:9px;letter-spacing:2px;text-align:center}@media(max-width:650px){.grid{grid-template-columns:1fr}.shell{padding:28px 18px}h1{letter-spacing:4px}}
</style></head>
<body><main class="shell"><div class="top"><span>ASGARD // SECURE TERMINAL</span><span id="conn">OFFLINE</span></div><h1>MJÖLNIR</h1><div class="sub">WORTHINESS EVALUATION SYSTEM™</div><section class="score"><div class="num" id="score">--</div><div class="label" id="verdict">AWAITING</div><div class="status" id="msg">Perform a motion to begin evaluation.</div></section><section class="grid"><div class="cell"><div class="key">MOTION</div><div class="value" id="motion">--</div></div><div class="cell"><div class="key">MODEL CONFIDENCE</div><div class="value" id="confidence">--</div></div><div class="cell"><div class="key">DEVICE</div><div class="value">ESP8266</div></div></section><div class="quote" id="quote">The hammer is currently judging you.</div><div class="foot">MPU6050 // TINYML // MJÖLNIR PROTOCOL</div></main>
<script>async function poll(){try{let r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw 0;let d=await r.json();conn.textContent='ONLINE';score.textContent=d.evaluated?d.score:'--';motion.textContent=d.motion||'--';confidence.textContent=d.evaluated?d.confidence.toFixed(1)+'%':'--';verdict.textContent=d.evaluated?(d.worthy?'WORTHY':'NOT WORTHY'):'AWAITING';msg.textContent=d.evaluated?(d.worthy?'The hammer has accepted you.':'Thor has declined your application.'):'Perform a motion to begin evaluation.';quote.textContent=d.evaluated?(d.worthy?'Mjölnir recognizes your potential.':'Your application has been rejected by Asgard.'):'The hammer is currently judging you.'}catch(e){conn.textContent='OFFLINE'}}poll();setInterval(poll,500);</script>
</body></html>
)rawliteral";
